### PR TITLE
Bugfix husky eslint linting errors

### LINKED ISSUE #28: Husky and linting errors on commit
There are some conflicts which have to be resolved. `drilbur` can't lint whysoever while `ralts` is able to do so. They share the same config so... idk. Somehow `drilbur` needs to have the `no-unused-var` rule set as described here: https://github.com/prettier/eslint-plugin-prettier/issues/306#issuecomment-783397862

Drilbur lint
grafik

Ralts lint
grafik

Also the `should be passed one day ago` test in `tonemato-utils` sometimes fails. It seems that has to do with some race condition, since between setting the date on `yesterday` and checking if a whole day has passed, there is so little time that it might actually fail.

### PR DESCRIPTION
**Pull request by robinduerhager**
Fixes #28

## Solutions
* Add `no-unused-var` so drilbur can lint, see: https://github.com/prettier/eslint-plugin-prettier/issues/306#issuecomment-783397862
* Add `.eslintignore`, so eslint does not try to lint unconfigured `packages`, see: https://github.com/okonet/lint-staged/issues/123#issuecomment-273438957
* Change `yesterday.getDate() - 1.1` to `yesterday.getDate() - 1` to widen the delta of the point in time being yesterday and checking if `now` is exactly one day ago.

### CODE REVIEW

File: packages/eslint-config-server/index.js [hunk 1]
```diff
@@ -9,5 +9,6 @@ module.exports = {
 
   rules: {
     'prettier/prettier': 'warn',
+    'no-unused-var': 0
```
Comment (ropfoo) [inline packages/eslint-config-server/index.js]: Ahhh yep I also had this in place before.. whats funny about it is, that lint-staged has no problem with that. 
So running:
```bash
npx lint-staged
```
will work perfectly fine on all apps. Mainly implemented the whole thing for running pre-commit linting so I did not test it for the standard eslint command again.
Not super happy with it but I guess its good enough for now.

BUT I think it should rather be 
```js
{
  ...
  'no-unused-vars': 0, // with an 's' at the end
}
```

File: .eslintignore [hunk 2]
```diff
@@ -0,0 +1 @@
+packages/
```
Comment (ropfoo) [inline .eslintignore]: but why? :D if there is no lint script specified the linter does not run in the first place...
I think we should also lint files in utils for example

**Review by ropfoo — CHANGES_REQUESTED** [review]

File: .eslintignore (hunk 2 above)
Comment (robinduerhager) [reply .eslintignore]: It's super weird, yesterday i wasn't able to commit any changes because of this, though today i saw that this error only happens if you change the corresponding package. The lint seems to be skipped for `tonemato-utils` if you just change an app.

Maybe yesterday pulling changes for this file or some formatting stuff triggered a lint? idk. Removing .eslintignore for now since this issue only occurs when modifying a package.

Comment (robinduerhager) [reply .eslintignore]: Here a picture of what happens if you change `tonemato-utils` and try to commit.
output_lint_packages

**Review by ropfoo — APPROVED** [review]

File: .eslintignore (hunk 2 above)
Comment (RopFoo) [reply .eslintignore]: weird... never happened to me

Comment (ropfoo) [reply .eslintignore]: ahhhh I know why... thats my bad I configured lint-staged to check that package but never set up eslint there :D gonna add a fix for that in a separate pr

Screenshot 2023-04-19 at 20 09 21

lel

Comment (ropfoo) [reply .eslintignore]: fixed in #30
